name: Release ESP-IDF Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32-c3 
          path: '.'
          command: |
            idf.py build
            cd build
            esptool.py --chip esp32c3 merge_bin -o release_firmware.bin @flash_args
            ls -R 

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_firmware.bin
          generate_release_notes: true
          fail_on_unmatched_files: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
